#include "Global.h"
#include "DefineGame.h"

//
//namespace GAME
//{
//	DIR_LOOKUP_TABLES[0] = { DIRECTIONS::LEFT, DIRECTIONS::LEFTTOP, DIRECTIONS::TOP, DIRECTIONS::RIGHTTOP, DIRECTIONS::RIGHT };
//	//{
//	//	{DIRECTIONS::LEFT, DIRECTIONS::LEFTTOP, DIRECTIONS::TOP, DIRECTIONS::RIGHTTOP, DIRECTIONS::RIGHT }				//TOP
//	//	,{DIRECTIONS::TOP, DIRECTIONS::RIGHTTOP, DIRECTIONS::RIGHT, DIRECTIONS::RIGHTBOTTOM, DIRECTIONS::BOTTOM }		//RIGHT
//	//	,{DIRECTIONS::LEFT, DIRECTIONS::LEFTBOTTOM, DIRECTIONS::BOTTOM, DIRECTIONS::RIGHTBOTTOM, DIRECTIONS::RIGHT }	//BOTTOM
//	//	,{DIRECTIONS::LEFT, DIRECTIONS::LEFTTOP, DIRECTIONS::TOP, DIRECTIONS::LEFTBOTTOM, DIRECTIONS::BOTTOM }			//LEFT
//	//	,{DIRECTIONS::TOP, DIRECTIONS::RIGHTTOP, DIRECTIONS::RIGHT }													//RIGHTTOP
//	//	,{DIRECTIONS::LEFT, DIRECTIONS::LEFTTOP, DIRECTIONS::TOP }														//LEFTTOP
//	//	,{DIRECTIONS::BOTTOM, DIRECTIONS::RIGHTBOTTOM, DIRECTIONS::RIGHT }												//RIGHTBOTTOM
//	//	,{DIRECTIONS::LEFT, DIRECTIONS::LEFTBOTTOM, DIRECTIONS::BOTTOM }												//LEFTBOTTOM
//	//};
//};
