#pragma once

namespace GAME
{
	enum class DIRECTIONS : int
	{
		DIRECTION_BEGIN = 0
		, STRAIGHT_BEGIN = DIRECTION_BEGIN  //직선 시작

		, TOP = STRAIGHT_BEGIN
		, RIGHT
		, BOTTOM
		, LEFT

		, STRAIGHT_END						//직선 끝
		, DIAGONAL_BEGIN = STRAIGHT_END		//대각선 시작		

		, RIGHTTOP = DIAGONAL_BEGIN
		, LEFTTOP
		, RIGHTBOTTOM
		, LEFTBOTTOM

		, DIAGONAL_END						//대각선 끝
		, DIRECTIONS_END = DIAGONAL_END

		, STRAIGHT_COUNT = STRAIGHT_END - STRAIGHT_BEGIN
		, DIAGONAL_COUNT = DIAGONAL_END - DIAGONAL_BEGIN
		, DIRECTIONS_COUNT = DIRECTIONS_END - DIRECTION_BEGIN		
		, INVALID = 100
	};

	enum class TILE_TYPE
	{
		 EMPTY
		,OBSTACLE
		,INVALID
	};

	using POS_INFO = std::tuple<int, int>;
	enum  POS_INFO_INDEX {POS_INFO_X, POS_INFO_Y};
};