#include "Global.h"
std::vector<GAME::DIRECTIONS> VEC_LOOK_UP_TABLE[static_cast<int>(GAME::DIRECTIONS::DIRECTIONS_COUNT)]
= 
{
	 { GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTTOP, GAME::DIRECTIONS::TOP, GAME::DIRECTIONS::RIGHTTOP, GAME::DIRECTIONS::RIGHT }
	,{ GAME::DIRECTIONS::TOP, GAME::DIRECTIONS::RIGHTTOP, GAME::DIRECTIONS::RIGHT, GAME::DIRECTIONS::RIGHTBOTTOM, GAME::DIRECTIONS::BOTTOM }
	,{ GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTBOTTOM, GAME::DIRECTIONS::BOTTOM, GAME::DIRECTIONS::RIGHTBOTTOM, GAME::DIRECTIONS::RIGHT }
	,{ GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTTOP, GAME::DIRECTIONS::TOP, GAME::DIRECTIONS::LEFTBOTTOM, GAME::DIRECTIONS::BOTTOM }
	,{ GAME::DIRECTIONS::TOP, GAME::DIRECTIONS::RIGHTTOP, GAME::DIRECTIONS::RIGHT }
	,{ GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTTOP, GAME::DIRECTIONS::TOP }
	,{ GAME::DIRECTIONS::BOTTOM, GAME::DIRECTIONS::RIGHTBOTTOM, GAME::DIRECTIONS::RIGHT }
	,{ GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTBOTTOM, GAME::DIRECTIONS::BOTTOM }	
};


std::vector<GAME::DIRECTIONS> VEC_ALL_DIRECTION = { GAME::DIRECTIONS::TOP, GAME::DIRECTIONS::RIGHTTOP, GAME::DIRECTIONS::RIGHT, GAME::DIRECTIONS::RIGHTBOTTOM, GAME::DIRECTIONS::BOTTOM, GAME::DIRECTIONS::LEFTBOTTOM, GAME::DIRECTIONS::LEFT, GAME::DIRECTIONS::LEFTTOP };